# version: "3"
# services:
#   aqkanji2koe:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     stdin_open: true
#     tty: true

version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
