version: "3"
services:
  aquestalk:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    entrypoint: /bin/bash -c "export LD_LIBRARY_PATH=/usr/local/lib:$$LD_LIBRARY_PATH && ./Main"
